name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: write

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go
    
    - name: Get and set versions from secret
      run: |
        echo ${{ github.event.head_commit.message }}
        echo ${{ vars.VERSION }}
        curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} "\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/keshavbhattad/bank/actions/variables/VERSION \
          -d '{"name":"VERSION","value":"0.3.0"}'

    - name: Install go-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.0-beta.1/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin
        which migrate
    
    - name: Run Migrations
      run: make migrateup

    - name: Test
      run: make test
